version: '3.9'

services:
  db:
    image: postgres:latest  
    container_name: student_db
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5430:5430"  
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
